language: ko-KR

early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai 요약"
  auto_title_placeholder: "@coderabbitai"
  poem: true
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!**/README.md"
    - "!**/.gitignore"
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    eslint:
      enabled: true
    prettier:
      enabled: true
    biome:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    ast-grep:
      packages: []
      rule_dirs: []
      util_dirs: []
      essential_rules: true
  chat:
    auto_reply: true
  knowledge_base:
    learnings:
      scope: auto
    issues:
      scope: auto
